### PR TITLE
fix(net): use Default initializer for heapless

### LINKED ISSUE #1827: Incompatible heapless version used to initialize embassy-net static configuration
### Summary

The version of embassy-net we use is using heapless v0.8.0, using heapless v0.9.1 breaks the type compatibility in `src/ariel-os-embassy/src/net.rs:249:26`. 

To reproduce the issue, you can run

```
laze -C examples/tcp-client/ build -b nrf52840dk -s ipv6   
```

### Relevant log output

```shell
   Compiling ariel-os-embassy v0.3.0 (/tmp/4133/ariel-os/src/ariel-os-embassy)
error[E0308]: mismatched types
   --> src/ariel-os-embassy/src/net.rs:249:26
    |
249 |             dns_servers: heapless::Vec::new(),
    |                          ^^^^^^^^^^^^^^^^^^^^ expected `Vec<Ipv6Address, 3>`, found `VecInner<_, _, ...>`
    |
    = note: expected struct `heapless::vec::Vec<Ipv6Addr, 3>`
               found struct `VecInner<_, _, vec::storage::VecStorageInner<[MaybeUninit<_>; _]>>`

```

### Hardware/ Setup

_No response_

### Possible Solution

_No response_

### Would you like to work on fixing this bug?

Maybe

### PR DESCRIPTION
**Pull request by nponsard**
# Description

This changes the `embassy-net` initialization to use `Default::default()` and thus removes the dependency on `heapless` in `ariel-os-embassy`.

## Testing

Tested with: 

```
CONFIG_NET_IPV6_STATIC_GATEWAY_ADDRESS=fd00::1 CONFIG_NET_IPV6_STATIC_ADDRESS=fd00::2 laze -C examples/tcp-echo/ build -d network-config-dhcp -b stm32u083c-dk  -s ipv6 run
```

## Issues/PRs References

- Fixes #1827 

## Change Checklist

- [x] The [commit history][conventional-commits] will be clean at the latest after applying [autosquash].
- [x] I have followed the [Coding Conventions][coding-conventions].
- [x] I have tested and performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.

[conventional-commits]: https://www.conventional-commits.org/en/v1.0.0/
[coding-conventions]: https://ariel-os.github.io/ariel-os/dev/docs/book/coding-conventions.html
[autosquash]: https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---autosquash

### CODE REVIEW

File: src/ariel-os-embassy/src/net.rs [hunk 1]
```diff
@@ -212,7 +212,7 @@ fn __ariel_os_network_config() -> embassy_net::Config {
 
             config.ipv4 = embassy_net::ConfigV4::Static(embassy_net::StaticConfigV4 {
                 address: embassy_net::Ipv4Cidr::new(ipaddr, PREFIX_LEN),
-                dns_servers: heapless::Vec::new(),
+                dns_servers: Default::default(),
```
Comment (ROMemories) [inline src/ariel-os-embassy/src/net.rs:219]: These should `expect` the `default_trait_access` lint (you can see the warning using the `clippy` laze task).

Comment (nponsard) [reply src/ariel-os-embassy/src/net.rs:219]: Ah I forgot that the `clippy` task was available, should be good now.
