### PR TITLE
fix(task-macro): make the `riot_rs::task` macro work with no parameters

### LINKED ISSUE #352: macros: `task` macro errors if there are no parameters
### Summary

If I understand correctly, using the task macro without any parameters should be valid code:
```rs
// Manually started task that doesn't require any peripherals or hooks.
#[riot_rs::task] 
fn my_task() {
...
}
```
The macro currently doesn't allow this.

### Relevant log output

```shell
error: unexpected end of input, expected an expression
  --> examples/threading-embassy/src/main.rs:12:1
   |
12 | #[riot_rs::task]
   | ^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the attribute macro `riot_rs::embassy::embassy_executor::task` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Hardware/ Setup

_No response_

### Possible Solution

_No response_

### Would you like to work on fixing this bug?

No

### PR DESCRIPTION
**Pull request by ROMemories**
# Description

The pool size was always specified in the Embassy `task` macro, in the generation code, but when the `autostart` and the `pool_size` parameters were not specified to the `riot_rs::task` macro, the pool size expression passed to that underlying Embassy task macro was a `None`, making the compilation fail with a syntax error in the generated code.

## Issues/PRs references

Fixes #352

## Open Questions

None

## Change checklist

- [x] I have cleaned up my commit history and squashed fixup commits.
- [x] I have followed the [Coding Conventions](../book/src/coding-conventions.md).
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.

### CODE REVIEW

File: src/riot-rs-macros/src/task.rs [hunk 1]
```diff
@@ -111,7 +111,7 @@ pub fn task(args: TokenStream, item: TokenStream) -> TokenStream {
             #task_function
         }
     } else {
-        let pool_size = attrs.pool_size;
+        let pool_size = attrs.pool_size.unwrap_or_else(|| syn::parse_quote! { 1 });
```
Comment (elenaf9) [inline src/riot-rs-macros/src/task.rs:114]: Could we add the info about this default value to the docs?

Comment (elenaf9) [reply src/riot-rs-macros/src/task.rs:114]: I don't think that's clear from the current documentation:
> - `pool_size`: (*optional*) set the maximum number of concurrent tasks that can be spawned for the function.

Based on these docs I would assume that per default there is no maximum number of tasks that can be spawned for the function.

**Review by kaspar030 — APPROVED** [review]
LGTM.
