### PR TITLE
fix(rt): move esp32c3 isr stack after .rwdata_dummy

### LINKED ISSUE #1438: Awaiting async functions doesn't work for esp32-c3-oled
### Summary

We are trying to use ariel-os with an esp32-c3 based development board.

We added
```yaml
  - name: espressif-esp32-c3-oledkit
    parent: esp-c3-mini-1
```
to laze-project.yml (we also tried the other esp32c3 variants as parent) and configured the pins in pins.rs for the blinky example, and to that point everything works.

What doesn't work is everything async, although it does work when just using embassy standalone.

Running a busy-loop as a delay gets the LED blinking; however, using anything async breaks it.

Async functions seem to get executed, but they never return.

We also tried with the pre-existing config (and corresponding hardware) `espressif-esp32-c6-devkitc-1`, where everything works as expected (no LED output, because it runs an RGB LED; however, the voltage on the corresponding pin does toggle).

Is there anything we missed in setting this up, or is this a bug?

### Relevant log output

```shell
laze -C examples/blinky build -b espressif-esp32-c3-oledkit run

laze: project root: /home/<user>/dev/NOG/ariel-os relpath: examples/blinky project_file: laze-project.yml
laze: building all for espressif-esp32-c3-oledkit
laze: reading cache: laze: build files have changed
laze: parsing 66 files took 6.282198ms
laze: stat'ing 66 files took 170.871µs
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of rp
configuring blinky for espressif-esp32-c3-oledkit
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of st-nucleo-c031c6
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of st-nucleo-f411re
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of st-nucleo-f767zi
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of bbc-microbit-v1
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of st-nucleo-wb55
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of st-nucleo-f401re
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of seeedstudio-lora-e5-mini
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of nrf52dk
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of particle-xenon
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of heltec-wifi-lora-32-v3
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of st-b-l475e-iot01a
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of nrf9160dk-nrf9160
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of nrf52840dk
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of st-nucleo-h755zi-q
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of bbc-microbit-v2
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of st-nucleo-f042k6
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of stm32u083c-dk
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of nrf5340dk
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of st-nucleo-wba55
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of nordic-thingy-91-x-nrf9151
app blinky: builder espressif-esp32-c3-oledkit is not an ancestor of st-steval-mkboxpro
configured 1 builds (took 863.201µs).
laze: writing cache took 179.197µs.
   Compiling ariel-os-embassy-common v0.2.0 (/home/<user>/dev/NOG/ariel-os/src/ariel-os-embassy-common)
   Compiling ariel-os-esp v0.2.0 (/home/<user>/dev/NOG/ariel-os/src/ariel-os-esp)
   Compiling ariel-os-hal v0.2.0 (/home/<user>/dev/NOG/ariel-os/src/ariel-os-hal)
   Compiling ariel-os-identity v0.2.0 (/home/<user>/dev/NOG/ariel-os/src/ariel-os-identity)
   Compiling ariel-os-embassy v0.2.0 (/home/<user>/dev/NOG/ariel-os/src/ariel-os-embassy)
   Compiling ariel-os v0.2.0 (/home/<user>/dev/NOG/ariel-os/src/ariel-os)
   Compiling blinky v0.0.0 (/home/<user>/dev/NOG/ariel-os/examples/blinky)
    Finished `release` profile [optimized + debuginfo] target(s) in 1.77s
     Running `espflash flash --monitor --log-format defmt ../../build/bin/espressif-esp32-c3-oledkit/cargo/riscv32imc-unknown-none-elf/release/blinky`
[2025-10-09T13:54:07Z INFO ] 🚀 A new version of espflash is available: v4.1.0
[2025-10-09T13:54:07Z INFO ] Serial port: '/dev/ttyACM0'
[2025-10-09T13:54:07Z INFO ] Connecting...
[2025-10-09T13:54:07Z INFO ] Using flash stub
Chip type:         esp32c3 (revision v0.4)
Crystal frequency: 40 MHz
Flash size:        4MB
Features:          WiFi, BLE
MAC address:       0c:4e:a0:63:1c:04
App/part. size:    81,520/4,128,768 bytes, 1.97%
[2025-10-09T13:54:08Z INFO ] Segment at address '0x0' has not changed, skipping write
[2025-10-09T13:54:08Z INFO ] Segment at address '0x8000' has not changed, skipping write
[00:00:00] [========================================]      15/15      0x10000                                                                                 [2025-10-09T13:54:08Z INFO ] Flashing has completed!
Commands:
    CTRL+R    Reset chip
    CTRL+C    Exit

ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0xe (SPI_FAST_FLASH_BOOT)
Saved PC:0x4038055a
0x4038055a - esp_hal::gpio::handle_pin_interrupts::{{closure}}
    at /home/<user>/.cargo/git/checkouts/esp-hal-56b75427f497a0b9-shallow/aa8d199/esp-hal/src/gpio/mod.rs:828
SPIWP:0xee
mode:DIO, clock div:2
load:0x3fcd5820,len:0x1714
load:0x403cc710,len:0x968
load:0x403ce710,len:0x2f9c
entry 0x403cc710
I (24) boot: ESP-IDF v5.1.2-342-gbcf1645e44 2nd stage bootloader
I (24) boot: compile time Dec 12 2023 10:50:58
I (25) boot: chip revision: v0.4
I (29) boot.esp32c3: SPI Speed      : 40MHz
I (34) boot.esp32c3: SPI Mode       : DIO
I (38) boot.esp32c3: SPI Flash Size : 4MB
I (43) boot: Enabling RNG early entropy source...
I (48) boot: Partition Table:
I (52) boot: ## Label            Usage          Type ST Offset   Length
I (59) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (67) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (74) boot:  2 factory          factory app      00 00 00010000 003f0000
I (82) boot: End of partition table
I (86) esp_image: segment 0: paddr=00010020 vaddr=3c010020 size=01654h (  5716) map
I (96) esp_image: segment 1: paddr=0001167c vaddr=3fc81854 size=00180h (   384) load
I (103) esp_image: segment 2: paddr=00011804 vaddr=40380000 size=00854h (  2132) load
I (112) esp_image: segment 3: paddr=00012060 vaddr=00000000 size=0dfb8h ( 57272) 
I (132) esp_image: segment 4: paddr=00020020 vaddr=42000020 size=03e20h ( 15904) map
I (136) boot: Loaded app from partition at offset 0x10000
```

### Hardware/ Setup

Host OS:        Linux
Rust-version: v1.92.0-nightly
Ariel OS:        Main branch, commit 8650ca0985add6b750d74ea6a7d848fac90794bc
Dev-board:    https://de.aliexpress.com/item/1005003557344025.html color: ESP32-C3-OLED
Probe-rs:       0.29.1
espflash:       3.3.0

### Possible Solution

_No response_

### Would you like to work on fixing this bug?

Yes

### PR DESCRIPTION
**Pull request by kaspar030**
# Description

This PR moves the isr stack after `.rwdata_dummy`, for esp32c3.

Doing this we lose the implicit stack protection, but this seems to be needed.

## Issues/PRs references

Fixes #1438.

## Change checklist

- [ ] I have cleaned up my commit history and squashed fixup commits.
- [ ] I have followed the [Coding Conventions](https://ariel-os.github.io/ariel-os/dev/docs/book/coding-conventions.html).
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.

### CODE REVIEW

File: src/ariel-os-rt/build.rs [hunk 1]
```diff
@@ -10,16 +10,17 @@ fn main() {
...
+            "esp32c3" => "INSERT AFTER .rwdata_dummy;",
             "cortex-m" => "INSERT BEFORE .data;",
             "riscv" => "INSERT BEFORE .trap;",
             _ => "",
         };
 
         let region = match context {
             "cortex-m" => "RAM",
-            "riscv" | "xtensa" => "RWDATA",
+            "riscv" | "xtensa" | "esp32c3" => "RWDATA",
```
Comment (ROMemories) [inline src/ariel-os-rt/build.rs:23]: optional: seems redundant as `esp32c3` is `riscv` (can be done in a follow-up as CI has already passed):
```suggestion
            "riscv" | "xtensa" => "RWDATA",
```

File: src/ariel-os-rt/build.rs [hunk 2]
```diff
@@ -10,16 +10,17 @@ fn main() {
     // Put the linker scripts somewhere the linker can find them
     let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
 
-    if let Some(context) = context_any(&["cortex-m", "riscv", "xtensa"]) {
+    if let Some(context) = context_any(&["esp32c3", "cortex-m", "riscv", "xtensa"]) {
         let insert_somewhere = match context {
+            "esp32c3" => "INSERT AFTER .rwdata_dummy;",
```
Comment (ROMemories) [inline src/ariel-os-rt/build.rs:15]: I'll need to update #1422.

Comment (ROMemories) [inline src/ariel-os-rt/build.rs:15]: For reference, the [`.rwdata_dummy` section is defined in `esp-hal`](https://github.com/esp-rs/esp-hal/blob/981379ede5613ac02cdeae9e1b1da00b1f82972c/esp-hal/ld/esp32c3/esp32c3.x#L35).

Comment (ROMemories) [inline src/ariel-os-rt/build.rs:15]: Do we have a way of making sure the issue is indeed because of this specific section and not just because this shifts the `.isr_stack` by a bit, not directly because of the shift specified by that section?

File: src/ariel-os-rt/build.rs (hunk 1 above)
Comment (kaspar030) [reply src/ariel-os-rt/build.rs:23]: doesn't `context_any` return the first matching context? So in `esp32c3` case, it is not `riscv`.

Comment (ROMemories) [reply src/ariel-os-rt/build.rs:23]: Ah ok, I missed that; fine then.

File: src/ariel-os-rt/build.rs (hunk 2 above)
Comment (kaspar030) [reply src/ariel-os-rt/build.rs:15]: Well, I'm beginning to understand the memory mapping, and indeed the previous location of the isr stack was colliding with `.rwdata`, which contains `.trap`. This was bound to crash on first ISR.
